// Enforcement home for the project's JSON-boundary rule (see CLAUDE.md):
// all external JSON must be parsed through a zod schema in src/lib/schemas.ts,
// so raw `JSON.parse` is banned everywhere else. Runs as part of `bun run build`
// (and therefore in the Android CI workflow) and standalone via `bun run lint`.
//
// The config is deliberately minimal — a parser plus the boundary rule — so a
// lint failure always means the JSON rule was broken, not style noise. Grow it
// intentionally if more rules are wanted.
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

export default tseslint.config(
  // src/router.ts is generated by generouted.
  { ignores: ["dist/**", "src-tauri/**", "node_modules/**", "src/router.ts"] },
  {
    files: ["**/*.{ts,tsx}"],
    extends: [tseslint.configs.base],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      "no-restricted-properties": [
        "error",
        {
          object: "JSON",
          property: "parse",
          message:
            "Raw JSON.parse is banned outside src/lib/schemas.ts — route external JSON " +
            "through parseJson + a zod schema there (see CLAUDE.md).",
        },
      ],
    },
  },
);
