use base64::Engine;
use tauri::Manager;
use tauri_plugin_sql::{Migration, MigrationKind};

const DB_URL: &str = "sqlite:tally.db";

/// Migrations are generated by drizzle-kit from `src/db/schema.ts`
/// (`bunx drizzle-kit generate --name <name>`) into `src-tauri/migrations/`.
/// Add each new file here with the next version number.
fn migrations() -> Vec<Migration> {
    vec![
        Migration {
            version: 1,
            description: "init",
            sql: include_str!("../migrations/0000_init.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "captures",
            sql: include_str!("../migrations/0001_captures.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 3,
            description: "garmin_workout_source",
            sql: include_str!("../migrations/0002_garmin_workout_source.sql"),
            kind: MigrationKind::Up,
        },
    ]
}

fn photos_dir(app: &tauri::AppHandle) -> Result<std::path::PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| e.to_string())?
        .join("photos");
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir)
}

/// Saves a base64-encoded JPEG into the app data dir and returns its filename.
#[tauri::command]
fn save_photo(app: tauri::AppHandle, data_base64: String) -> Result<String, String> {
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(data_base64.as_bytes())
        .map_err(|e| e.to_string())?;
    let dir = photos_dir(&app)?;
    let millis = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|e| e.to_string())?
        .as_millis();
    let name = format!("{millis}.jpg");
    std::fs::write(dir.join(&name), bytes).map_err(|e| e.to_string())?;
    Ok(name)
}

/// Reads a stored photo back as base64. Used by the background agent —
/// fetching the asset URL from the WebView is blocked by CSP on Android.
#[tauri::command]
fn read_photo(app: tauri::AppHandle, filename: String) -> Result<String, String> {
    if filename.contains('/') || filename.contains('\\') || filename.contains("..") {
        return Err("invalid filename".into());
    }
    let path = photos_dir(&app)?.join(filename);
    let bytes = std::fs::read(path).map_err(|e| e.to_string())?;
    Ok(base64::engine::general_purpose::STANDARD.encode(bytes))
}

#[tauri::command]
fn delete_photo(app: tauri::AppHandle, filename: String) -> Result<(), String> {
    if filename.contains('/') || filename.contains('\\') || filename.contains("..") {
        return Err("invalid filename".into());
    }
    let path = photos_dir(&app)?.join(filename);
    if path.exists() {
        std::fs::remove_file(path).map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Prepares a destination path for a database export: clears old exports and
/// returns the absolute path the frontend should `VACUUM INTO` (the snapshot
/// itself must be written by SQLite for consistency with the live WAL).
#[tauri::command]
fn prepare_db_export(app: tauri::AppHandle, file_name: String) -> Result<String, String> {
    if file_name.contains('/') || file_name.contains('\\') || file_name.contains("..") {
        return Err("invalid file name".into());
    }
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| e.to_string())?
        .join("exports");
    // VACUUM INTO refuses to overwrite; start from an empty dir.
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir.join(file_name).to_string_lossy().into_owned())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations(DB_URL, migrations())
                .build(),
        )
        .plugin(tauri_plugin_fasting::init())
        .plugin(tauri_plugin_health_connect::init())
        .plugin(tauri_plugin_share::init())
        .invoke_handler(tauri::generate_handler![
            save_photo,
            read_photo,
            delete_photo,
            prepare_db_export
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
